apiVersion: v2
appVersion: 4.0.3
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 9.8.12
description: A Helm chart for powerdns with admin and postgresql
keywords:
- dns
- powerdns
maintainers:
- email: frank@theysm.site
  name: Frank Beutelschiess
name: powerdns
sources:
- https://gitea.thesym.site/infra/helmPowerDns
- https://harbor.thesym.site/harbor/projects/5/summary
type: application
version: 0.1.0
