###
##
# * TASKFILE
##  https://taskfile.dev
###
version: '3'

vars:
  message:  Tasks concerning the cluster

tasks:

  taskDebug:
    desc: show all variables in Taskfile
    cmds:
      - |
        echo -e \
        "\n{{range $key, $value := .}} {{$key }}:  \e[92m{{$value}}\e[0m\n {{end}}\n"
    silent: true


  default:
    desc: display info
    cmds:
      - |
        echo -e \
        "\n{{.message}}\n"
      - |
        task -l
    silent: true


###
##
# ** ALPHABETICAL
##
###
  getImagesUsedClusterwideAll:
    desc: "list all images which are available in the cluster"
    cmds:
      - |
        kubectl get pods --all-namespaces -o jsonpath="{..image}" |\
        tr -s '[[:space:]]' '\n' |\
        sort |\
        uniq -c
    silent: true
