###
##
# * TASKFILE
##  https://taskfile.dev
###
version: '3'

vars:
  message:  Tasks concerning the cluster

tasks:

  taskDebug:
    desc: show all variables in Taskfile
    cmds:
      - |
        echo -e \
        "\n{{range $key, $value := .}} {{$key }}:  \e[92m{{$value}}\e[0m\n {{end}}\n"
    silent: true


  default:
    desc: display info
    cmds:
      - |
        echo -e \
        "\n{{.message}}\n"
      - |
        task -l
    silent: true


###
##
# ** MISC
##
###
  getImagesUsedClusterwideAll:
    desc: "list all images which are available in the cluster"
    cmds:
      - |
        kubectl get pods --all-namespaces -o jsonpath="{..image}" |\
        tr -s '[[:space:]]' '\n' |\
        sort |\
        uniq -c
    silent: true


  k8sUpgrade:
    desc: " TODO upgrade the cluster"
    cmds:
      - |
        swapoff -a
    silent: true


#  resourcesNamespacedGetwithXargs:
#    desc: "get all resources from current namespace"
#    cmds:
#      - |
#        kubectl api-resources --verbs=list --namespaced -o name \
#        | xargs -n 1 kubectl get --show-kind --ignore-not-found


  resourcesNamespacedGet:
    desc: "get all resources from current namespace"
    cmds:
      - |
        for APIRESOURCES in `kubectl api-resources --verbs=list --namespaced -o name`; do
        RES=$(kubectl get --show-kind --ignore-not-found ${APIRESOURCES})
        [[ ! -z ${RESOURCES} ]] && echo -e "\x1b[33m${APIRESOURCES}\x1b[0m\n${RESOURCES}\n"; 
        done
    silent: true


###
##
# ** INSTALLATION
##
###
  installHelmPush:
    ### cf. https://github.com/chartmuseum/helm-push
    desc: "helm: install helm-push"
    cmds:
      - |
        helm plugin install https://github.com/chartmuseum/helm-push
    silent: true


  installHelmSecrets:
    ### cf. https://github.com/jkroepke/helm-secrets
    desc: "helm: install helm-secrets"
    cmds:
      - |
        helm plugin install https://github.com/jkroepke/helm-secrets
    silent: true


  installKubectlKrew:
    ### cf. https://krew.sigs.k8s.io/docs/user-guide/setup/install/
    ### for plugins see: https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md
    desc: "kubectl: install krew"
    cmds:
      - |
        (
          cd "$(mktemp -d)" &&
          curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz" &&
          tar zxvf krew.tar.gz &&
          KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_$(uname -m | sed -e 's/x86_64/amd64/' -e 's/arm.*$/arm/')" &&
          "$KREW" install krew
        )
    silent: true


  installKubectlPluginGopass:
    ### cf. https://github.com/gopasspw/kubectl-gopass
    desc: "kubectl: install gopass-plugin"
    cmds:
      - |
        kubectl krew install gopass
    silent: true


###
##
# ** REPOSITORY
##
###
  repositoryGitHookLinkCreate:
    desc: "create a symlink from GIT/hooks to .git/hooks"
    cmds:
      - |
        rm -r ./.git/hooks
        ln -srf ./GIT/hooks/ ./.git/hooks
    silent: true
