{{- range $shard, $e := until (int $.Values.shardCount) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: {{ $.Values.web.name }}
    scope: jitsi
    shard: {{ $shard | quote}}
  name: shard-{{ $shard }}-{{ $.Values.web.name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ $.Values.web.name }}
      scope: jitsi
      shard: {{ $shard | quote}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: {{ $.Values.web.name }}
        scope: jitsi
        shard: {{ $shard | quote}}
    spec:
      containers:
      - env:
        - name: DISABLE_HTTPS
          value: "1"
        - name: HTTP_PORT
          value: "80"
        - name: XMPP_SERVER
          value: shard-{{ $shard }}-{{ $.Values.prosody.name }}
        - name: JICOFO_AUTH_USER
          value: focus
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: XMPP_BOSH_URL_BASE
          value: http://shard-{{ $shard }}-{{ $.Values.prosody.name }}:5280
        - name: XMPP_MUC_DOMAIN
          value: muc.meet.jitsi
        - name: TZ
          value: Europe/Prague
        - name: JVB_TCP_HARVESTER_DISABLED
          value: "true"
        image: {{ $.Values.web.image }}
        imagePullPolicy: {{ $.Values.web.imagePullPolicy }}
        name: web
        readinessProbe:
          httpGet:
            port: 80
        resources:
          limits:
            cpu: 400m
            memory: 300Mi
          requests:
            cpu: {{ $.Values.web.resources.requests.cpu }}
            memory: {{ $.Values.web.resources.requests.memory }}
            # cpu: 400m
            # memory: 300Mi
        volumeMounts:
        - mountPath: /usr/share/jitsi-meet/plugin.head.html
          name: web
          subPath: plugin.head.html
        - mountPath: /defaults/config.js
          name: web
          subPath: config.js
        - mountPath: /defaults/interface_config.js
          name: web
          subPath: interface_config.js
        {{- if $.Values.web.watermark }}
        - mountPath: /usr/share/jitsi-meet/images/watermark.png
          name: watermark
          subPath: watermark.png
        {{ end }}
      volumes:
      - configMap:
          items:
          - key: plugin.head.html
            path: plugin.head.html
          - key: config.js
            path: config.js
          - key: interface_config.js
            path: interface_config.js
          name: web
        name: web
      {{- if $.Values.web.watermark }}
      - configMap:
          items:
          - key: watermark.png
            path: watermark.png
          name: watermark
        name: watermark
      {{ end }}
{{ end }}
