---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    #storage: 1Gi
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/PERSISTENCE/traefik"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-pv-claim
  namespace: traefik
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      #storage: 1Gi
      storage: 128Mi
