---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: "basic-deny"
  namespace: "ambassador"
spec:
  External:
    auth_service: "deny-all"
    ### useage after creation of access-service
    # auth_service: "access.access:80"      
    path_prefix:  "/deny"
     
     
     
     
     
### ---
### apiVersion: getambassador.io/v2
### kind: Filter
### metadata:
###   name: "basic-deny"
###   namespace: "ambassador"
### spec:
###   External:
###     auth_service:       "deny-all"    ### required
###     # tls:                bool                ### optional; default is true if `auth_service` starts with "https://" (case-insensitive), false otherwise
###     proto:              "https"       ### optional; default is "http"
###     # timeout_ms:         integer             ### optional; default is 5000
###     # allow_request_body: bool                ### deprecated; use include_body instead
###     # include_body:                           ### optional; default is null
###     #   max_bytes:          integer           ### required
###     #   allow_partial:      bool              ### required
###     # status_on_error:                        ### optional
###     #   code:               integer           ### optional; default is 403
###     # failure_mode_allow: bool                ### optional; default is false
### 
###     # ### the following are used only if `proto: http`; they are ignored if `proto: grpc`
### 
###     # path_prefix:                   "/path"  ### optional; default is ""
###     # allowed_request_headers:                ### optional; default is []
###     # - "x-allowed-input-header"
###     # allowed_authorization_headers:          ### optional; default is []
###     # - "x-input-headers"
###     # - "x-allowed-output-header"
###     # add_linkerd_headers:           bool     ### optional; default is false
###     #
