apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-admin
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
spec:
  type: {{ .Values.powerdnsadmin.service.type }}
  ports:
    - port: {{ .Values.powerdnsadmin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "powerdnsadmin.selectorLabels" . | nindent 4 }}
