apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  namespace: cert-manager
  name: challenge-mapping
spec:
  prefix: /.well-known/acme-challenge/
  rewrite: ""
  service: challenge-service
---
apiVersion: v1
kind: Service
metadata:
  namespace: cert-manager
  name: challenge-service
spec:
  ports:
  - port: 80
    targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"
