* MATTERMOST
** INFO
*** DATABASE
    Do not manipulate the Mattermost database directly.
    Mattermost is designed to stop working if data integrity is compromised.
    Any manipulation of the database must be done using the built in command line tools.
*** SOURCES
    https://github.com/mattermost/mattermost-helm
*** PLUGINS
**** Installation
     Download a Plugin to ...PERSISTENCE/mattermost/plugins
     Enable it in the Taskfile.yml
**** Configuration
    Due to the readonly config.json
    keys and values have to be taken from the DevTools
    Send a request from https://msg.thesym.site/admin_console/plugins/plugin_jitsi (SAVE)
    look for the PUT-Request in DevTools
    filter for Plugin
    take the config and apply it to the Taskfile.yml
**** Jitsi
      https://github.com/mattermost/mattermost-plugin-jitsi/
** TODO TODOS
** Erledigtes
*** DONE Passwords
**** mysql
*** DONE Persistence
**** 3x
*** DONE Keys
**** Every `helm upgrade` will generate a new set of keys unless it is set manually like this:
     #+begin_src yaml
     configJSON:
       EmailSettings:
         InviteSalt: vcvS4ih7AEUwdrFCCvyFOCWxk32wK2YY
       FileSettings:
         PublicLinkSalt: BY17tl6SaIBR7Rmr3f3Gtp3nWogQQlwT
       SqlSettings:
         AtRestEncryptKey: N7XqTN7pWj2orQQn8G6Znobf8EdmkJQf
     #+end_src
***** cf. CHART/mattermost-team-edition/templates/_warnings.tpl
****** all three keys are created by "randAlphaNum 3
****** use `task chartDebug` to generate keys
