shardCount: 2
namespace: jitsi
haproxy:
  name: haproxy
  image: haproxy:2.1
  ingressEnable: true
  ingress:
    host: jitsi.domain.org
    tlsEnable: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
jicofo:
  name: jicofo
  image: jitsi/jicofo
  imagePullPolicy: Always
  resources:
    requests:
      cpu:     400m
      memmory: 400Mi
jvb:
  name: jvb
  replicas: 1
  image: jitsi/jvb
  imagePullPolicy: Always
  monitoringEnable: true
  resources:
    requests:
      cpu:     1500m
      memmory: 1000Mi
  monitoring:
    imagePullPolicy: Always
    resources:
      requests:
        cpu:     100m
        memmory: 100Mi
prosody:
  name: prosody
  image: jitsi/prosody
  imagePullPolicy: Always
  resources:
    requests:
      cpu:     300m
      memmory: 300Mi
web:
  name: web
  image: jitsi/web
  imagePullPolicy: Always
  resources:
    requests:
      cpu:     400m
      memmory: 300Mi
  ## If you want to use your own custom watermark, first create configmap from your png file: `kubectl create configmap -n <namespace> watermark --from-file=watermark.png`
  watermark: true
  config:
    watermarkLink: "https://example.org"
    appName: jitsi
    nativeAppName: jitsi
    providerName: example.org


JICOFO_AUTH_PASSWORD: ""
JICOFO_COMPONENT_SECRET: ""
JVB_AUTH_PASSWORD: ""
JVB_STUN_SERVERS: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
TURN_HOST: meet-jit-si-turnrelay.jitsi.net
TURN_PORT: "4446"
TURNS_PORT: "443"
