###
##
# * TASKFILE
##  https://taskfile.dev
###
version: '3'

vars:

  name:                     gitea

  nameSpace:                "{{.name}}"

  domainName:               "{{.name}}.thesym.site"
  chartRepoUrl:             https://dl.gitea.io/charts/
  chartRepoName:            gitea-charts
  chartName:                "{{.name}}"

  filter:     "basic-allow"                                                    ### NOT WORKING; NOT implemented yet
  # filter:     "basic-auth"
  # filter:     "basic-deny"                                                     ###     WORKING; NOT implemented properly -> redirect to thesym.site
  ### filter:     "ory"                                                          ### NOT WORKING; NOT implemented yet

  labelTier:                devOps

  hostCertStaging:          ""                                                 ### letsencrypt
  # hostCertStaging:          true                                               ### letsencryptStaging
  hostAcmeEmail:            "fbeutelschiess@gmail.com"

  mappingPort:              3000
  mappingServiceName:       "{{.name}}-http"

  portforwardingPortSource: "3000"
  portforwardingPortTarget: "22"

  pvName0:                  "{{.name}}-data"
  pvName1:                  "data-{{.name}}-postgresql-0"
  pvRelativePath0:          "{{.name}}/data"
  pvRelativePath1:          "{{.name}}/db"
  pvStorageSize0:           10Gi
  pvStorageSize1:           10Gi
  pvStorageClass0:          local-path
  pvStorageClass1:          local-path


  templateDebugTarget:       "ingress"

  message:                   Tasks for {{.name}}{{if .chartName}}-helm{{end}}

  chartSecretsExist:         true
  # chartSecretsExist:         false
  chartVariablesSet: |-
    --set resources.requests.cpu=10m \
    --set persistence.existingClaim={{.pvName0}} \
    --set gitea.config.APP_NAME=Gitea \
    --set gitea.config.server.DOMAIN={{.domainName}} \
    --set gitea.config.server.ROOT_URL=https://{{.domainName}} \
    --set gitea.config.server.SSH_DOMAIN={{.domainName}} \


tasks:

  taskDebug:
    desc: show all variables in Taskfile
    cmds:
      - |
        echo -e \
        "\n{{range $key, $value := .}} {{$key }}:  \e[92m{{$value}}\e[0m\n {{end}}\n"
    silent: true


  default:
    desc: display info
    cmds:
      - |
        echo -e \
        "\n{{.message}}\n"
      - |
        task -l
    silent: true


###
##
# ** SEQUENCE
##
###
  1:
    desc: ( repoAdd )
    cmds:
      - task: repoAdd
    silent: true


  2:
    desc: ( chartGet )
    cmds:
      - task: chartGet
    silent: true


  3:
    desc: ( namespaceApply )
    cmds:
      - task: namespaceApply
    silent: true


  4:
    desc: ( filterPolicyApply )
    cmds:
      - task: filterPolicyApply
    silent: true


  5:
    desc: ( hostApply )
    cmds:
      - task: hostApply
    silent: true


  6:
    desc: ( mappingApply )
    cmds:
      - task: mappingApply
    silent: true


  7:
    desc: ( persistenceApply )
    cmds:
      - task: persistenceApply
    silent: true


  8:
    desc: ( sshConnectionEnable )
    cmds:
      - task: sshConnectionEnable
    silent: true


  9:
    desc: ( chartInstall )
    cmds:
      - task: chartInstall
    silent: true


  10:
    desc: ( chartUpdate )
    cmds:
      - task: chartUpdate
    silent: true


  11:
    desc: ( resourcesRemove )
    cmds:
      - task: resourcesRemove
    silent: true


###
##
# ** ALPHABETICAL
##
###
  chartDebug:
    desc: debug chart
    cmds:
      - |
        helm install \
        --namespace {{.nameSpace}} \
        --dry-run \
        --debug \
        {{.name}} CHART/{{.chartName}} \
        {{.chartVariablesSet}}
    silent: true


  chartGet:
    desc: download the chart
    cmds:
      - |
        helm pull \
        {{.chartRepoName}}/{{.chartName}} \
        -d CHART \
        --untar
    silent: true


  chartInstall:
    desc: install chart
    cmds:
      - |
        helm \
        {{- if eq .chartSecretsExist "true"}}
        secrets \
        {{- end}}
        install \
        {{.name}} CHART/{{.chartName}} \
        --namespace {{.nameSpace}} \
        {{.chartVariablesSet}}
        {{- if eq .chartSecretsExist "true"}}
        -f sec.yaml
        {{- end}}
    silent: true


  chartUpdate:
    desc: update chart
    cmds:
      - |
        helm \
        {{- if eq .chartSecretsExist "true"}}
        secrets \
        {{- end}}
        upgrade \
        --namespace {{.nameSpace}} \
        {{.name}} CHART/{{.chartName}} \
        {{.chartVariablesSet}}
        {{- if eq .chartSecretsExist "true"}}
        -f sec.yaml
        {{- end}}
    silent: true


  chartRemove:
    desc: (chartUninstall + namespaceDelete + persistentVolumeDelete)
    cmds:
      - task: chartUninstall
      - task: namespaceDelete
      - task: persistentVolumeDelete
    silent: true


  chartUninstall:
    desc: uninstall the {{.name}}-chart
    cmds:
      - |
        helm --namespace {{.nameSpace}} uninstall {{.name}}
    silent: true


  filterPolicyApply:
    desc: create the host for {{.name}}
    cmds:
      - |
        cat <<EOF | kubectl apply -f -
        apiVersion: getambassador.io/v2
        kind: FilterPolicy
        metadata:
          name: {{.name}}
          namespace: {{.nameSpace}}
        spec:
          rules:
          - host: {{.domainName}}
            path: "*"
            filters:
            #- name: {{.filter}}
            - name: {{if eq .filter "basic-allow"}}"basic-auth"{{else}}{{.filter}}{{end}}
              namespace: "ambassador"
              {{- if eq .filter "basic-allow"}}
              onDeny:  "continue"
              onAllow: "continue"
              {{- end}}
        EOF
    silent: true


  hostApply:
    desc: apply the host for {{.name}}
    cmds:
      - |
        cat <<EOF | kubectl apply -f -
        apiVersion: getambassador.io/v2
        kind: Host
        metadata:
          name: {{.name}}
          namespace: ambassador-hosts
        spec:
          hostname: {{.domainName}}
          acmeProvider:
            {{- if .hostCertStaging }}
            authority: https://acme-staging-v02.api.letsencrypt.org/directory
            {{- else}}
            authority: https://acme-v02.api.letsencrypt.org/directory
            {{- end}}
            email: {{.hostAcmeEmail}}
            privateKeySecret:
              name: {{.name}}{{- if .hostCertStaging }}Staging{{- end}}Key
          tlsSecret:
            name: {{.name}}
          requestPolicy:
            insecure:
              action: Redirect
        EOF
    silent: true


  mappingApply:
    desc: apply the mapping for {{.name}}
    cmds:
      - |
        cat <<EOF | kubectl apply -f -
        apiVersion: getambassador.io/v2
        kind: Mapping
        metadata:
          name: {{.name}}
          namespace: {{.nameSpace}}
        spec:
          prefix: /
          #service: {{.name}}-service.{{.nameSpace}}:{{.mappingPort}}
          service: {{.mappingServiceName}}.{{.nameSpace}}:{{.mappingPort}}
          host: {{.domainName}}
        EOF
    silent: true


  namespaceApply:
    desc: apply the namespace {{.nameSpace}}
    cmds:
      - |
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Namespace
        metadata:
          name: {{.nameSpace}}
          labels:
            name: {{.nameSpace}}
            tier: {{.labelTier}}
        EOF
    silent: true


  namespaceDelete:
    desc: delete the namespace {{.nameSpace}}
    cmds:
      - |
        kubectl delete namespace {{.nameSpace}}
    silent: true


  portforward:
    desc: portforwarding for {{.name}}
    cmds:
      - |
        kubectl port-forward --namespace {{.nameSpace}} $(kubectl get pod -l app.kubernetes.io/name={{.name}} -o name) {{.portforwardingPortSource}}:{{.portforwardingPortTarget}}
    silent: true


  persistenceApply:
    desc: apply persistence for {{.name}}
    cmds:
      ### database
      - |
        {{- if .pvName0 }}
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: PersistentVolume
        metadata:
          name: {{.pvName0}}
          labels:
            type: local
        spec:
          storageClassName: {{.pvStorageClass0}}
          capacity:
            storage: {{.pvStorageSize0}}
          accessModes:
            - ReadWriteOnce
          hostPath:
            path: "/PERSISTENCE/{{.pvRelativePath0}}"
        ---
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: {{.pvName0}}
          namespace: {{.nameSpace}}
        spec:
          volumeName: {{.pvName0}}
          storageClassName: {{.pvStorageClass0}}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{.pvStorageSize0}}
        EOF
        {{- end }}

        {{- if .pvName1 }}
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: PersistentVolume
        metadata:
          name: {{.pvName1}}
          labels:
            type: local
        spec:
          storageClassName: {{.pvStorageClass1}}
          capacity:
            storage: {{.pvStorageSize1}}
          accessModes:
            - ReadWriteOnce
          hostPath:
            path: "/PERSISTENCE/{{.pvRelativePath1}}"
        #---
        #apiVersion: v1
        #kind: PersistentVolumeClaim
        #metadata:
        #  name: {{.pvName1}}
        #  namespace: {{.nameSpace}}
        #spec:
        #  volumeName: {{.pvName1}}
        #  storageClassName: {{.pvStorageClass1}}
        #  accessModes:
        #    - ReadWriteOnce
        #  resources:
        #    requests:
        #      storage: {{.pvStorageSize1}}
        EOF
        {{- end }}
    silent: true


  persistentVolumeDelete:
    desc: delete the pv(s) for {{.name}}
    cmds:
      - |
        {{- if .pvName0 }}
        kubectl delete pv {{.pvName0}}
        {{- end }}
        {{- if .pvName1 }}
        kubectl delete pv {{.pvName1}}
        {{- end }}
    silent: true


  repoAdd:
    desc: add the repository
    cmds:
      - |
        helm repo add \
        {{.chartRepoName}} \
        {{.chartRepoUrl}}
      - |
        helm repo update
    silent: true


  resourcesRemove:
    desc: (namespaceDelete + persistentVolumeDelete)
    cmds:
      - task: namespaceDelete
      - task: persistentVolumeDelete
    silent: true


  templateDebug:
    desc: "debug template; USAGE: `task templateDebug templateDebugTarget=admin`; DEFAULT: ingress"
    cmds:
      - |
        helm template \
        --namespace {{.nameSpace}} \
        ./CHART/{{.chartName}} \
        --debug \
        -s templates/{{.templateDebugTarget}}.yaml \
        {{.chartVariablesSet}}
    silent: true


###
##
# ** CUSTOM
##
###
  sshConnectionEnable:
    desc: "debug template; USAGE: `task templateDebug templateDebugTarget=admin`; DEFAULT: ingress"
    cmds:
      - |
        cat <<EOF | kubectl apply -f -
        ---
        apiVersion: getambassador.io/v2
        kind:  TCPMapping
        metadata:
          name:  "{{.name}}-ssh"
          namespace: {{.nameSpace}}
        spec:
          port: 8022
            #host: "{{.domainName}}"
          service: "{{.name}}-ssh.{{.nameSpace}}:22"
        EOF
    silent: true


  giteaBackup:
    desc: "create backup of gitea NOTworking"
    cmds:
      - |
        echo "
          # Execute the following commands:

          kex -n gitea gitea-0 -- sh

          chmod 777 /data/ssh/*

          cd app/gitea
          su git
          gitea dump -c /data/gitea/conf/app.ini
          exit

          chmod 600 /data/ssh/*
          exit

          kubectl -n gitea cp gitea-0:app/gitea/gitea-dump-1618488953.zip /home/frank/k3s/BAK/gitea-dump-1618488953.zip
          exit

          # 20h++
          scp nuc:/home/frank/k3s/BAK/gitea-dump-1618488953.zip /home/frank/BAK/gitea/
          (unzip gitea-dump-1618488953.zip)

          # result: (>11G)

          # INFO: https://docs.gitea.io/en-us/backup-and-restore/

           "
    silent: true
